# Generated by Django 2.2.3 on 2019-07-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_ip', models.CharField(max_length=50)),
                ('personal_height', models.IntegerField(unique=True, verbose_name='身高(/cm)')),
                ('personal_weight', models.IntegerField(unique=True, verbose_name='体重(/kg)')),
                ('personal_bmi', models.IntegerField(unique=True, verbose_name='BMI')),
            ],
        ),
    ]
