# Generated by Django 2.2.3 on 2019-07-25 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BMI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_information',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='时间'),
            preserve_default=False,
        ),
    ]
