# Generated by Django 2.2.3 on 2019-07-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI', '0002_personal_information_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='personal_bmi',
            field=models.IntegerField(verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='personal_height',
            field=models.IntegerField(verbose_name='身高(/cm)'),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='personal_weight',
            field=models.IntegerField(verbose_name='体重(/kg)'),
        ),
    ]
