# Generated by Django 2.2.3 on 2019-07-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI', '0003_auto_20190725_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='personal_bmi',
            field=models.FloatField(verbose_name='BMI'),
        ),
    ]
