# Generated by Django 2.2.3 on 2019-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI', '0004_auto_20190725_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='personal_bmi',
            field=models.FloatField(max_length=4, verbose_name='BMI'),
        ),
    ]
